language: node_js

node_js:
  - "stable"

cache:
  directories:
    - spa/node_modules

script:
  - sh ./build.sh

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token
  local_dir: spa/dist
  on:
    branch: master
